### ISSUE TITLE
2. NEN

### ISSUE THREAD

**Issue by hanbinChen97** [MouYongli/MedKGC#4]
- [ ] ground truth construction
- [ ] ontology construction
  - 研究UMLS里面到底包含了哪些信息。 
  - get a radiology subset
    - (A2) Conceptual Entity, like clear
    - (A1.2) Anatomical Structure , like lobe
    - (B2) Phenomenon or Process, like Pneumothorax
- [ ] method development
  - 如何结合不同level的信息，word level，sentence level...

**Comment by JohannHalley** [comment]
如何结合不同level的信息，word level，sentence level...

**Comment by JohannHalley** [comment]
研究DB
Radlex里面到底包含了哪些信息。

**Comment by JohannHalley** [comment]
- [ ] 1. target ontology
  - a subset of UMLS
- [ ] 2. evaluation data (UKA)
- [ ] 3. method

**Comment by hanbinChen97** [comment]
**Doing**
- subset

**Today**
- subset not done yet, but some solutions found.
- look up item from UMLS with api, 

**ToDo**
- subset use python tools

**Comment by hanbinChen97** [comment]
A
├── A1 Physical Object
│   ├── A1.2 Anatomical Structure
│   │   ├── A1.2.2 Anatomical Abnormality
│   │   │   ├── A1.2.2.1 Congenital Abnormality
│   │   │   └── A1.2.2.2 Acquired Abnormality
│   │   └── A1.2.3 Fully Formed Anatomical Structure
│   │       ├── A1.2.3.1 Body Part, Organ, or Organ Component
│   │       ├── A1.2.3.2 Tissue
│   │       └── A1.2.3.4 Cell Component
│   ├── A1.3 Manufactured Object
│   │   └── A1.3.1 Medical Device
│   └── A1.4 Substance
│       ├── A1.4.1 Chemical
│       │   ├── A1.4.1.1 Chemical Viewed Functionally
│       │   │   ├── A1.4.1.1.1 Pharmacologic Substance
│       │   │   ├── A1.4.1.1.3 Immunologic Factor
│       │   │   │   └── A1.4.1.1.3.5 Immunologic Factor
│       │   │   └── A1.4.1.1.5 Hazardous or Poisonous Substance
│       │   └── A1.4.1.2 Chemical Viewed Structurally
│       │       └── A1.4.1.2.1 Organic Chemical
│       └── A1.4.2 Body Substance
├── A2 Conceptual Entity
│   ├── A2.1 Idea or Concept
│   │   ├── A2.1.1 Temporal Concept
│   │   ├── A2.1.2 Qualitative Concept
│   │   ├── A2.1.3 Quantitative Concept
│   │   ├── A2.1.4 Functional Concept
│   │   │   └── A2.1.4.1 Body System
│   │   └── A2.1.5 Spatial Concept
│   │       ├── A2.1.5.1 Body Space or Junction
│   │       └── A2.1.5.2 Body Location or Region
│   ├── A2.2 Finding
│   │   └── A2.2.1 Laboratory or Test Result
│   ├── A2.3 Organism Attribute
│   │   └── A2.3.1 Clinical Attribute
│   ├── A2.4 Intellectual Product
│   └── A2.9 Group
│       └── A2.9.5 Patient or Disabled Group
└── B Event
    ├── B1 Activity
    │   ├── B1.1 Behavior
    │   │   └── B1.1.1 Social Behavior
    │   └── B1.3 Occupational Activity
    │       ├── B1.3.1 Health Care Activity
    │       │   ├── B1.3.1.2 Diagnostic Procedure
    │       │   └── B1.3.1.3 Therapeutic or Preventive Procedure
    │       └── B1.3.2 Research Activity
    └── B2 Phenomenon or Process
        ├── B2.2 Natural Phenomenon or Process
        │   └── B2.2.1 Biologic Function
        │       ├── B2.2.1.1 Physiologic Function
        │       │   ├── B2.2.1.1.1 Organism Function
        │       │   └── B2.2.1.1.4 Molecular Function
        │       └── B2.2.1.2 Pathologic Function
        │           └── B2.2.1.2.1 Disease or Syndrome
        │               └── B2.2.1.2.1.1 Mental or Behavioral Dysfunction
        └── B2.3 Injury or Poisoning

**Comment by hanbinChen97** [comment]
embedding 目前不太行，可能后续还是需要RadLex作为target Ontology。
1. 用bm25的简单方法来检索初步结果。
2. 现在用prompt的方法结合candidates来进行。

**Comment by hanbinChen97** [comment]
TODOs:
- [x] 描述一下你的方法（API和形态学，OpenAI GPT，然后这两个如何整合）。(Oerleaf)
- [x] 800个entity中，
  - [x] 第一，有多少是human标的是nan，你的方法也是nan（看一下这些entity的特点是什么）。
  - [x] 第二，有多少是human标的是nan，但是你的方法link了cui。
  - [x] 第三，有多少是human标的和你的方法标的是一致的cui（不是第一种情况）。
  - [x] 第四，有多少是human标的和你的方法标的不是一致的cui。
  - [x] 第五，有多少是human标的cui但是你的方法出来的是nan。
- [x] 140万个相关的umls的concepts，你要表达的是什么，他们用来干什么。

**Comment by hanbinChen97** [comment]
方法链接了CUI，人工标注为nan（13个例子）：

Bibasilar, overlying, support, Stable, SVC, changed, median, elongation, Lower, secondary, free, expanded, port

特点：

这些词大多是描述性的医学术语或解剖位置。  
有些是相对普通的词（如changed, free, expanded），没有什么医学特殊含义。  
一些词（如Bibasilar, SVC）是非常专业的医学术语，但是目前还没被准确定义和收录。

方法链接了CUI，但人工修正了CUI（9个例子）：

Cardiac, severity, worrisome, constant, OPACITIES, Median, minor, internal jugular central venous

特点：

这些词大多是有多重含义或在不同上下文中可能有不同解释的术语。  
有些词（如Cardiac, OPACITIES）是广泛的医学概念，可能有多个相关但不同的CUI。  
一些词（如worrisome, constant）在医学和日常用语中有不同的含义。

方法标注了nan，人工标注了CUI（4个例子）：

the Swan - Ganz, advanced, appreciable, first

特点：

这些词包括专有名词（Swan - Ganz）和一些在医学上下文中可能有特殊含义的普通词（advanced, appreciable, first）。  
可能是因为这些词在不同上下文中有不同的含义，导致方法难以确定正确的CUI。


人工标注和方法都是nan的情况（152个例子，列举一些典型的）：

 well - expanded, in acceptable position, by several centimeters, implement, medially, not well seen, less prominent, on waterseal, partially assessed, tiny, existing, regressed, gross, lateral structures, elevate, transverse, portions, posteriorly, displacement, obliquity of the patient, shift, Poor definition, not as well seen on this study, 4 cm above, lucency, assessment, opacified, alongside, elongated, increse, collections, sharp, subcutaneus, deeper, 1-2 mm, A, rod, overlies, fixation, 3 cm above, developing, Developing, Support, in

特点：

包含了大量的描述性术语和短语，这些可能太具体或上下文相关，难以映射到标准化的医学概念。  
许多是解剖位置的描述或医疗设备的位置描述。  
有些是相对普通的词，没有什么医学特殊含义。  
包含了一些非常具体的测量值（如 "5 cm above", "3.5 cm"）。  
有一些是一般性的描述词（如 "partially", "minimally", "essentially"），在医学上下文中可能有特殊含义，但不易标准化。  
包含了一些医学缩写（如 "AP", "IJ"）和专有名词（如 "Swan"）。  
有一些复合词或短语（如 "well - expanded", "not well seen"）可能难以映射到单一的标准化概念。

**Comment by hanbinChen97** [comment]
## UMLS子集（1.4百万概念）的局限性

1. **数据库规模过大**
   - 1.4百万个相关UMLS概念过于庞大
   - 不适合建立高效的本地向量数据库

2. **检索方法局限性**
   - 使用BM25或形态学检索方法
   - 相当于重新实现UMLS API，意义不大

3. **覆盖范围过广**
   - 对于胸部放射学领域来说，UMLS子集覆盖面过于宽泛
   - 可能引入不必要的噪音和复杂性

## Radlex数据库的优势

1. **适当的规模**
   - 仅包含约46,000个概念
   - 更适合建立嵌入式向量数据库

2. **领域特异性**
   - 专注于放射学领域
   - 更符合胸部放射学研究的需求

## 当前方法

- 目前使用UMLS API进行检索
- 利用UMLS提供的库和检索方法

## 未来方向

- 考虑转向使用Radlex数据库进行实验
- 探索在Radlex基础上建立本地向量数据库的可能性

**Comment by hanbinChen97** [comment]
- [x] 补充一个图来表示我们现在的data format；
- [x] 根据metrics制定表格，accuracy，precission，recall，f1
- [x] 针对morphological matching的结果和semantic matching的结果；
- [x] results下面分析错误的一些情况；
- [x] extends data from radgraph
- [ ] discussions讨论limitation；
- [ ] conclusion讨论future work。

**Comment by hanbinChen97** [comment]
TP：test 和 result 都非空且值相等
FP：(test 为空且 result 非空) 或 (两者都非空但值不相等)
FN：test 非空但 result 为空
TN：test 和 result 都为空

1. 
Accuracy: 0.6608
Precision: 0.9940
Recall: 0.5404
F1: 0.7001
True positives: 495
False positives: 3
False negatives: 421
True negatives: 331

2.
Accuracy: 0.9584
Precision: 0.9797
Recall: 0.9624
F1: 0.9710
True positives: 870
False positives: 18
False negatives: 34
True negatives: 328
